
name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.20.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0

  # HTTP & Networking
  http: ^0.14.0
  url_launcher: ^6.3.1
  android_intent_plus: ^3.1.0

  # Audio & Speech
  audioplayers: ^3.1.2
  flutter_spinkit: ^5.2.1
  speech_to_text: ^4.4.0
  permission_handler: ^11.4.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.13

  # Charts
  fl_chart: ^0.60.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Hive code generator
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/call_bg.jpg
    - assets/doctor1.jpg
    - assets/doctor2.jpg
    - assets/doctor3.jpg
    - assets/doctor4.jpg
    - assets/doctor5.jpg
    - assets/doctor6.jpg
    - assets/doctor7.jpg
    - assets/doctor8.jpg
    - assets/doctor9.jpg
    - assets/doctor10.jpg
    - assets/doctor11.jpg
    - assets/doctor12.jpg
    - assets/doctor13.jpg
    - assets/doctor14.jpg
    - assets/doctor15.jpg
    - assets/doctor16.jpg
    - assets/doctor17.jpg
    - assets/doctor18.jpg
    - assets/doctor19.jpg
    - assets/doctor20.jpg
    - assets/doctor21.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
